// <auto-generated />
using System;
using BLL.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BLL.Migrations
{
    [DbContext(typeof(SQLContext))]
    [Migration("20190725160016_suggest")]
    partial class suggest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BLL.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Entity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Entity");
                });

            modelBuilder.Entity("BLL.Email", b =>
                {
                    b.HasBaseType("BLL.Entity");

                    b.Property<int>("Code");

                    b.Property<bool>("IsActivate");

                    b.ToTable("Email");

                    b.HasDiscriminator().HasValue("Email");
                });

            modelBuilder.Entity("BLL.Suggest", b =>
                {
                    b.HasBaseType("BLL.Entity");

                    b.Property<int?>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<string>("Title");

                    b.HasIndex("AuthorId");

                    b.ToTable("Suggest");

                    b.HasDiscriminator().HasValue("Suggest");
                });

            modelBuilder.Entity("BLL.User", b =>
                {
                    b.HasBaseType("BLL.Entity");

                    b.Property<int?>("EmailId");

                    b.Property<int>("Integral");

                    b.Property<string>("PassWord");

                    b.Property<string>("UserName");

                    b.HasIndex("EmailId");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("BLL.Suggest", b =>
                {
                    b.HasOne("BLL.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("BLL.User", b =>
                {
                    b.HasOne("BLL.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId");
                });
#pragma warning restore 612, 618
        }
    }
}
